Feature
panqqq/java-collections-treemap pull request #1
Opened 2022-09-19 08:35 UTC by panqqq

2022-09-20 08:02 UTC, eldlit requested changes

2022-09-20 08:02 UTC, eldlit commented on src/main/java/com/endava/internship/collections/Student.java
> +            return -(dateOfBirth.compareTo(student.dateOfBirth));
please check this line

2022-09-20 08:02 UTC, eldlit commented on src/main/java/com/endava/internship/collections/StudentMap.java
> +        //Works
please remove all `//works` comments

2022-09-20 08:36 UTC, panqqq commented on src/main/java/com/endava/internship/collections/Student.java
> +            return -(dateOfBirth.compareTo(student.dateOfBirth));
Thank you, resolved!

2022-09-22 08:02 UTC, eldlit approved these changes

2022-09-22 08:12 UTC, merged